//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWA_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesktopCases
    {
        public int Id { get; set; }
        public Nullable<int> CaseRef { get; set; }
        public string PlatformRef { get; set; }
        public string Address { get; set; }
        public string Postcode { get; set; }
        public Nullable<decimal> EstimatedVal { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<decimal> OriginalLTV { get; set; }
        public string PropertyType { get; set; }
        public string PropertyStyle { get; set; }
        public Nullable<int> Beds { get; set; }
        public string Tenure { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.Guid> SurveyorFK { get; set; }
        public Nullable<decimal> CalculatedVal { get; set; }
        public Nullable<decimal> SurveyorValuation { get; set; }
        public Nullable<decimal> NewLTV { get; set; }
        public string ComparablesLink { get; set; }
    }
}
