//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWA_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilestreamFiles
    {
        public System.Guid Id { get; set; }
        public byte[] File { get; set; }
        public string FileName { get; set; }
    }
}
