//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWA_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public System.Guid ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<System.Guid> UserType { get; set; }
        public Nullable<int> FailCount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> MFAPIN { get; set; }
        public Nullable<System.Guid> FirmID { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsExternal { get; set; }
        public Nullable<int> ActiveStep { get; set; }
        public Nullable<System.Guid> ResetUID { get; set; }
        public Nullable<System.Guid> UserStatus { get; set; }
        public Nullable<System.Guid> BSMid { get; set; }
        public Nullable<bool> IsTestUser { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    }
}
